import './babel/babel'
import '@scr/cart'
import '@scr/tabs'
import '@scr/sort'
import '@scr/db/db.json'
import './styles/style'
import './styles/common/root'
import './styles/common/header'
import './styles/common/main'
import '@img/logo'
import '@img/basket'
import '@img/burger-pizza'
import '@img/arrow-left'
import '@img/burger'
import '@img/cart'
import '@img/cheese-pizza'
import '@img/chicken-pizza'
import '@img/shrimps-pizza'
import '@img/cross'
import '@img/minus'
import '@img/plus'
import '@img/rubbish'
import '@img/truck'
import '@img/smile.jpg'
import '@img/arrow'


